zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loading from master file dynamic/managed-keys.bind failed: file not found
managed-keys-zone ./IN: loaded serial 0
running
zone 1.168.192.in-addr.arpa/IN: Transfer started.
transfer of '1.168.192.in-addr.arpa/IN' from 192.168.1.110#53: connected using 192.168.1.120#34046
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 199.7.83.42#53
error (network unreachable) resolving './DNSKEY/IN': 2001:7fd::1#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
zone 1.168.192.in-addr.arpa/IN: transferred serial 2016051803
transfer of '1.168.192.in-addr.arpa/IN' from 192.168.1.110#53: Transfer completed: 1 messages, 9 records, 267 bytes, 0.040 secs (6675 bytes/sec)
zone 1.168.192.in-addr.arpa/IN: sending notifies (serial 2016051803)
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.5.5.241#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.203.230.10#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:1::803f:235#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.33.4.12#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.5.5.241#53
zone linux-library.com/IN: Transfer started.
transfer of 'linux-library.com/IN' from 192.168.1.110#53: connected using 192.168.1.120#37907
zone linux-library.com/IN: transferred serial 2016051803
transfer of 'linux-library.com/IN' from 192.168.1.110#53: Transfer completed: 1 messages, 8 records, 218 bytes, 0.004 secs (54500 bytes/sec)
zone linux-library.com/IN: sending notifies (serial 2016051803)
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 128.63.2.53#53
error (network unreachable) resolving './NS/IN': 2001:7fd::1#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 192.36.148.17#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 202.12.27.33#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving './NS/IN': 2001:500:2f::f#53
error (network unreachable) resolving './NS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (unexpected RCODE REFUSED) resolving './DNSKEY/IN': 192.58.128.30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (unexpected RCODE REFUSED) resolving 'dlv.isc.org/DNSKEY/IN': 128.63.2.53#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:7fd::1#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:503:c27::2:30#53
error (unexpected RCODE REFUSED) resolving './NS/IN': 193.0.14.129#53
managed-keys-zone ./IN: Unable to fetch DNSKEY set '.': failure
managed-keys-zone ./IN: Unable to fetch DNSKEY set 'dlv.isc.org': failure
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.5.5.241#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 202.12.27.33#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 198.41.0.4#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 128.8.10.90#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.33.4.12#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.203.230.10#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 192.112.36.4#53
error (unexpected RCODE REFUSED) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (unexpected RCODE REFUSED) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.228.79.201#53
error (unexpected RCODE REFUSED) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 192.58.128.30#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'D.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'G.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'E.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'C.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 199.7.83.42#53
error (unexpected RCODE REFUSED) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 192.36.148.17#53
error (unexpected RCODE REFUSED) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 193.0.14.129#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'I.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'L.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (unexpected RCODE REFUSED) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 128.63.2.53#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'B.ROOT-SERVERS.NET/AAAA/IN': 2001:500:1::803f:235#53
shutting down
no longer listening on 192.168.1.120#53
no longer listening on ::1#53
exiting
